"""Added phone number column

Revision ID: 3d14dc9c862b
Revises: 5bd9f0e94dcf
Create Date: 2025-05-27 22:36:19.222763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d14dc9c862b'
down_revision: Union[str, None] = '5bd9f0e94dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###
