"""Edit: Added location column in the company table

Revision ID: 560ecab6750d
Revises: adfb22d0f637
Create Date: 2025-06-29 11:55:54.477871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560ecab6750d'
down_revision: Union[str, None] = 'adfb22d0f637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(length=128), nullable=False))
    op.add_column('staff', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('phoneNumber', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'staff', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'phoneNumber')
    op.drop_column('staff', 'email')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
